### ISSUE TITLE
Document mercy rules

### ISSUE THREAD

**Issue by Pugzy** [PGMDev/Website#11]
Document the newly added `mercy` element for the score module https://github.com/PGMDev/PGM/pull/601.

Great feature btw https://github.com/PGMDev/PGM/commit/70c139f3094195b68477180bce7ab645a9e6267b

**Comment by Indicardo** [comment]
Fixed in https://github.com/PGMDev/Website/commit/334ae850a028b748517e5e7075f359b6b0f72fa2.
