### ISSUE TITLE
Document events plugin

### ISSUE THREAD

**Issue by Pablete1234** [PGMDev/Website#12]
The events plugin now available at https://github.com/PGMDev/Events has little documentation in it's readme, it'd be nice for pgm.dev to get a section of documentation about that XML format, and possibly setting up config files etc

**Comment by Indicardo** [comment]
Isn't the README self-explanatory enough? I think the plugin just needs exposure in some way or another

**Comment by Pablete1234** [comment]
The readme could use the expanding into a proper docs page wich uses the same tables as PGM to define elements, and sections, as well as more examples. also a section for how to setup the remaining things on it would be nice

**Comment by Indicardo** [comment]
Added in https://github.com/PGMDev/Website/commit/57450348df4a113ace68d63efb3491d0b5250fa4.
