### ISSUE TITLE
Filters Documentation mentioning Elytras which are no longer supported

### ISSUE THREAD

**Issue by IcedCode** [PGMDev/Website#17]
![image](https://user-images.githubusercontent.com/7426927/91214750-688adc80-e6c8-11ea-8acb-77f6385a240d.png)
On https://pgm.dev/docs/modules/mechanics/filters it mentions Elytra which is not supported in 1.8 minecraft, so wouldn't be supported in the current PGM. Hence should be removed.

**Comment by Indicardo** [comment]
Fixed in https://github.com/PGMDev/Website/commit/141499f5b68d2e50e6cf484f97509eebf2b4e0f2. Thanks for contributing!
