### ISSUE TITLE
Document overtime

### ISSUE THREAD

**Issue by Pablete1234** [PGMDev/Website#19]
`<time overtime="1m" max-overtime="15m">12m</time>`

The match will last 12 minutes, if when timelimit reaches 0 the teams are tied, a one-minute overtime starts. If the tie is broken and no team makes a comeback, the 1m ticks down. The overtime will last a maximum of 15 minutes, when approaching 15 minutes it will tick down and will end regardless.

**Comment by harvanchik** [comment]
This can be closed now. 😄

**Comment by Indicardo** [comment]
Thank you for contributing!
