### ISSUE TITLE
Issue with text in dark mode

### ISSUE THREAD

**Issue by CrazyisCreeps** [PGMDev/Website#23]
Not sure how to fix or would attempt to, but https://pgm.dev/docs/reference/misc/formatting#chat-colors in dark mode doesn't correctly swap the numbers and letters above each coloured squared (right below "Chat Colors") when swapped to dark mode and makes it super hard to read

**Comment by Indicardo** [comment]
That's simply because it's an image and not actual text. The solution would be creating a new one

**Comment by CoWinkKeyDinkInc** [comment]
Resolved in 3c9205bd89ef929b497b3aa5ed826b16e4ed3c11
