### ISSUE TITLE
Document blitz filters

### ISSUE THREAD

**Issue by Pugzy** [PGMDev/Website#27]
https://github.com/PGMDev/PGM/commit/6de56512b8c9ebe9e41fd2394ff6e4499fd29cac

Examples found on issue https://github.com/PGMDev/PGM/pull/744

**Comment by KingOfSquares** [comment]
Mine is better >:(

**Comment by CoWinkKeyDinkInc** [comment]
Documented in 384e9da1c010a9cee449fb9e517f21c6d551cf6d
