### ISSUE TITLE
Document flag posts

### ISSUE THREAD

**Issue by Pugzy** [PGMDev/Website#3]
A recent commit from mrcookie allows flag posts to be named these should be documented.

https://github.com/PGMDev/PGM/commit/63b166d4014a2c7737610a2b09d3f0ee08c4a51f

**Comment by Indicardo** [comment]
Fixed in https://github.com/PGMDev/Website/commit/f89fbffd530f083520c3888b1f878dd5e7e65cea. Let me know if I missed something. Thanks for reporting!
