### ISSUE TITLE
Potion effect documentation is incomplete

### ISSUE THREAD

**Issue by alexsosnovsky** [PGMDev/Website#34]
The chart found at https://pgm.dev/docs/reference/items/potions doesn't show all the potion effects available to mapmakers.

It should be updated to match the official Spigot list: https://helpch.at/docs/1.8.8/org/bukkit/potion/PotionEffectType.html

**Comment by CoWinkKeyDinkInc** [comment]
What is listed in the Spigot docs that aren't on the PGM docs are status effects, which are not potion effects. The status effects are `ABSORPTION`, `BLINDNESS`, `CONFUSION`, `FAST_DIGGING`, `HEALTH_BOOST`, `SATURATION`, `SLOW_DIGGING`, and `WITHER`. The point of this table is mostly to help map makers pick a certain colour for their custom potions. It does turn out you can make a potion with a wither status effect so I'll add that to the page.

https://minecraft.gamepedia.com/Java_Edition_data_values/Pre-flattening#Potions
