### ISSUE TITLE
The link to the Blitz XML is a dead link

### ISSUE THREAD

**Issue by IcedCode** [PGMDev/Website#5]
On the page https://pgm.dev/docs/modules/objectives/blitz/ the link to the Blitz XML is a dead link, returns a GitHub 404 as that no longer exists. (https://maps.oc.tc/Blitz/blitz-global.xml)

**Comment by Indicardo** [comment]
Sorry for the wait. This has been fixed in https://github.com/PGMDev/Website/commit/ea04bbc0d0c837f534d07ee8121688137a3bf1d2.
