### ISSUE TITLE
Add example to Player Count Filter

### ISSUE THREAD

**Issue by OhPointFive** [PGMDev/Website#51]
The Player Count Filter doesn't currently have an example, which would be helpful.

**Comment by CoWinkKeyDinkInc** [comment]
The player count filter has not been reintroduced to PGM, though there was a closed [pull request](https://github.com/PGMDev/PGM/pull/699/files) that would've done this, which you may take a look in and readapt this. Perhaps do you mean this?

https://github.com/PGMDev/PGM/blob/3d28b3b0c5fb68d944c59a2c8669ffd7fd5282a8/core/src/main/java/tc/oc/pgm/filters/FilterParser.java#L613

**Comment by Pablete1234** [comment]
Player count filter has been reintroduced at this time

**Comment by CoWinkKeyDinkInc** [comment]
The example has been added in d5b0c1b.
