### ISSUE TITLE
Document <king> module

### ISSUE THREAD

**Issue by Cazadorian** [PGMDev/Website#55]
\<king> is a module that despite being depreciated is still used by a large number of maps, especially KotH maps made originally for competitive use due to mapmakers copying the standardised hill XML used by maps such as Smoke and Cobalt. The control points page currently lists some info specific to the module under it's KotH defaults header, but the page makes no direct mention of what \<king> actually is.

The main difference between \<king> and \<control-points> is simply the different default values that the points have. \<king> also allows usage of \</king> under score, which originally prevented kills from giving points on a KotH map but now has no function despite still existing within PGM as kills no longer give points by default.

The original documentation related to \<king> can be found within these two archived pages of docs.oc.tc

[Most recent archive that still lists info about \<king>](https://web.archive.org/web/20160823205036/https://docs.oc.tc/modules/gamemode_koth)

[Older archive that has less info but lists the purpose of \</king> before it was depreciated](https://web.archive.org/web/20140412031923/http://docs.oc.tc/modules/gamemode_koth)

**Comment by CoWinkKeyDinkInc** [comment]
Documented in 9c8a25e37c99d4a921adc0774a90038cba7fb091.
