### ISSUE TITLE
Grass labeled as dead shrub

### ISSUE THREAD

**Issue by CrazyisCreeps** [PGMDev/Website#79]
https://github.com/PGMDev/Website/blob/master/docs/reference/items/inventory.mdx
https://pgm.dev/docs/reference/items/inventory

Item ID 31, 31:0 is labeled as a "Dead Shrub" when it is in fact the Grass item. The Dead Bush item has the ID of 32.

Very minor but it confused me for a minute so I thought I'd share. Never figured out how to sign off commits or I'd open a PR

**Comment by CoWinkKeyDinkInc** [comment]
"Shrub" (31:0) and "Dead Bush" (32) are separate but almost visually identical items. The more commonly known Dead Bush can only be placed on Sand Blocks while the Shrub can be placed on Grass blocks, but can't be placed on Sand. The Shrub is visually closer to the ground than the Dead Bush block is. The Grass item is called "Tall Grass" and the ID is 31:1.

So there is a difference, and the items can't be stacked. I checked in WorldEdit.
