### ISSUE TITLE
Document observing, alive and dead player filters

### ISSUE THREAD

**Issue by RuedigerLP** [PGMDev/Website#83]
`<observing/>` is missing as the inverse of `<participating/>` .
https://github.com/PGMDev/PGM/blob/dev/core/src/main/java/tc/oc/pgm/filters/matcher/player/ParticipatingFilter.java

`<alive/>` and `<dead/>` are missing as well.
https://github.com/PGMDev/PGM/blob/dev/core/src/main/java/tc/oc/pgm/filters/matcher/player/PlayerStateFilter.java

**Comment by CoWinkKeyDinkInc** [comment]
Thanks for sharing the sources in the code!
