### ISSUE TITLE
Document message attribute of after filter

### ISSUE THREAD

**Issue by RuedigerLP** [PGMDev/Website#86]
`<after duration="" message="">`
Also `<after>` should not be listed as an operator but under "Mechanisms".

https://docs.oc.tc/modules/filters#countdown
https://github.com/PGMDev/PGM/blob/dev/core/src/main/java/tc/oc/pgm/filters/parse/FilterParser.java#L529-L537

**Comment by CoWinkKeyDinkInc** [comment]
Documented in 79425c05cd4779354a33600340f372e7df92fef9
