### ISSUE TITLE
Document other missing filters (rank and countdown, fill action, subtitle typo)

### ISSUE THREAD

**Issue by RuedigerLP** [PGMDev/Website#89]
- [x] `<rank>` Match if the player or team's rank is within the specified range.

`<rank>` and `<score>` can also have an team attribute.

https://docs.oc.tc/modules/filters#rank_score
https://github.com/PGMDev/PGM/blob/dev/core/src/main/java/tc/oc/pgm/filters/parse/FilterParser.java#L539-L543

- [x] `<countdown>`

https://docs.oc.tc/modules/filters#countdown
https://github.com/PGMDev/PGM/blob/dev/core/src/main/java/tc/oc/pgm/filters/parse/FilterParser.java#L519-L527

- [x] `<fill>` Fill action

https://github.com/PGMDev/PGM/blob/dev/core/src/main/java/tc/oc/pgm/action/ActionParser.java#L283-L290

- [x] `subtitle` attribute of `<message>` action is called `subtitle` and not `text`.

https://github.com/PGMDev/PGM/blob/dev/core/src/main/java/tc/oc/pgm/action/ActionParser.java#L225

- [x] `spread-teammates` attribute of `spawn` Spawn players as far away as possible from any players, event teammates.

- [x]  `<holding/>`, `<carrying/>` and `<wearing/>` are dynamic filters.

- [x] `exposed` If true an action can be triggered using `/action trigger [action]`

https://github.com/PGMDev/PGM/pull/1102

**Comment by CoWinkKeyDinkInc** [comment]
https://github.com/PGMDev/PGM/pull/1138 and 
https://github.com/PGMDev/PGM/pull/1149 have also been documented.

**Comment by CoWinkKeyDinkInc** [comment]
All of these have been added. Thanks so much for linking all the relevant information!
